#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
# Don't load libunionpreload.so, see PrusaSlicer GH #3388
#export UNION_PRELOAD="${HERE}"
#export LD_PRELOAD="${HERE}/libunionpreload.so"
export PATH="${HERE}"/usr/bin/:"${HERE}"/usr/sbin/:"${HERE}"/bin/:"${HERE}"/sbin/:"${PATH}"
export LD_LIBRARY_PATH="${HERE}"/usr/lib/:"${HERE}"/usr/lib/i386-linux-gnu/:"${HERE}"/usr/lib/x86_64-linux-gnu/:"${HERE}"/usr/lib32/:"${HERE}"/usr/lib64/:"${HERE}"/lib/:"${HERE}"/lib/i386-linux-gnu/:"${HERE}"/lib/x86_64-linux-gnu/:"${HERE}"/lib32/:"${HERE}"/lib64/:"${LD_LIBRARY_PATH}"
# Allow symlinking the AppImage and invoking the corresponding binary depending on which
# symlink was used to invoke the AppImage.
if [ ! -z $APPIMAGE ] ; then
    # Invoked from inside an AppImage.
    BINARY_NAME=$(basename "$ARGV0")
    if [ -e "$HERE/usr/bin/$BINARY_NAME" ] ; then
	exec "$HERE/usr/bin/$BINARY_NAME" "$@"
    else
	exec "$HERE/usr/bin/prusa-slicer" "$@"
    fi
else
    # Not invoked from inside an AppImage.
    exec "$HERE/usr/bin/prusa-slicer" "$@"
fi

